### ISSUE TITLE
support for NeuroArch data model

### ISSUE THREAD

**Issue by lebedov** [neurokernel/neurodriver#1]
The following changes must be made to support loading of graphs of executable entities and ports in accordance with NeuroArch's data model:

- Only ports should have selectors; neuron and synapse model instances may not.
- Ports may be connected to synapses so that they can 
  - receive data from external inputs or presynaptic neurons in other LPUs or
  - emit output to be recorded.
- Required neuron model attributes:
  - ``spiking`` - True if the neuron's output is boolean, False if it
    is floating point.
  - ``model`` - Model name.
  Comments: The currently required public and extern attributes will be
  eliminated in light of the new requirement that all external input/output
  to/from neurons/synapses must be performed via ports. Since not all models support emission of 
  both spikes and graded potential values, sanity checking needs to be performed to 
  exclude unsupported combinations of the above attributes.
- Required synapse model attributes:
  - ``reverse`` - Reverse potential. If present, the synapse's output is
    a conductance; if absent it is a current.
  Comments: The class attribute will be eliminated because Neurodriver can
  implicitly determine whether presynaptic and postsynaptic neurons are spiking
  from their attributes. The conductance attribute will be eliminated because
  the presence/absence of the reverse attribute signifies whether the synapse
  emits conductance or current values.

**Comment by nikulukani** [comment]
Fixed in models-abstraction branch. Points 2-4 are not relevant in the new design

**Comment by lebedov** [comment]
👍
