### ISSUE TITLE
create new Component parent class for BaseNeuron and BaseSynapse

### ISSUE THREAD

**Issue by lebedov** [neurokernel/neurodriver#2]
Given that the current neuron and synapse classes in Neurodriver are not readily extensible to support constructs with more complex input/output relationships (e.g., presynaptic inhibition), we should introduce the notion of a Component that provides an abstract framework that supports aspect common to all such constructs.

An important design consideration that needs to be addressed when implementing the above is imposing an order on the state variable updates performed for each component type.

Copying @nikulukani.

**Comment by nikulukani** [comment]
Fixed in the new models-abstraction branch
